jobs:
- name: u16cppall-test
  type: runSh
  steps:
    - TASK:
        runtime:
          options:
            imageName: "drydock/aarch64_u16cppall"
            imageTag: master
        script:
          - gcc --version
          - autoconf --version
          - automake --version
          - ccache --version
          - clang --version
